In [ ]:
import pandas as pd
import numpy as np
import re

In [ ]:
df = pd.read_csv("train.csv").drop(columns=['ID'])

In [ ]:
df.columns

Index(['시술 시기 코드', '시술 당시 나이', '임신 시도 또는 마지막 임신 경과 연수', '시술 유형', '특정 시술 유형',
       '배란 자극 여부', '배란 유도 유형', '단일 배아 이식 여부', '착상 전 유전 검사 사용 여부',
       '착상 전 유전 진단 사용 여부', '남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인',
       '여성 부 불임 원인', '부부 주 불임 원인', '부부 부 불임 원인', '불명확 불임 원인', '불임 원인 - 난관 질환',
       '불임 원인 - 남성 요인', '불임 원인 - 배란 장애', '불임 원인 - 여성 요인', '불임 원인 - 자궁경부 문제',
       '불임 원인 - 자궁내막증', '불임 원인 - 정자 농도', '불임 원인 - 정자 면역학적 요인',
       '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태', '배아 생성 주요 이유', '총 시술 횟수',
       '클리닉 내 총 시술 횟수', 'IVF 시술 횟수', 'DI 시술 횟수', '총 임신 횟수', 'IVF 임신 횟수',
       'DI 임신 횟수', '총 출산 횟수', 'IVF 출산 횟수', 'DI 출산 횟수', '총 생성 배아 수',
       '미세주입된 난자 수', '미세주입에서 생성된 배아 수', '이식된 배아 수', '미세주입 배아 이식 수', '저장된 배아 수',
       '미세주입 후 저장된 배아 수', '해동된 배아 수', '해동 난자 수', '수집된 신선 난자 수', '저장된 신선 난자 수',
       '혼합된 난자 수', '파트너 정자와 혼합된 난자 수', '기증자 정자와 혼합된 난자 수', '난자 출처', '정자 출처',
       '난자 기증자 나이', '정자 기증자 나이', '동결 배아 사용 여부', '신선 배아 사용 여부', '기증 배아 사용 여부',
       '대리모 여부', 'PGD 시술 여부', 'PGS 시술 여부', '난자 채취 경과일', '난자 해동 경과일',
       '난자 혼합 경과일', '배아 이식 경과일', '배아 해동 경과일', '임신 성공 여부'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256351 entries, 0 to 256350
Data columns (total 68 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   시술 시기 코드               256351 non-null  object
 1   시술 당시 나이               256351 non-null  object
 2   임신 시도 또는 마지막 임신 경과 연수  9370 non-null    float64
 3   시술 유형                  256351 non-null  object
 4   특정 시술 유형               256349 non-null  object
 5   배란 자극 여부               256351 non-null  int64
 6   배란 유도 유형               256351 non-null  object
 7   단일 배아 이식 여부            250060 non-null  float64
 8   착상 전 유전 검사 사용 여부       2718 non-null    float64
 9   착상 전 유전 진단 사용 여부       250060 non-null  float64
 10  남성 주 불임 원인             256351 non-null  int64
 11  남성 부 불임 원인             256351 non-null  int64
 12  여성 주 불임 원인             256351 non-null  int64
 13  여성 부 불임 원인             256351 non-null  int64
 14  부부 주 불임 원인             256351 non-null  int64
 15  부부 부 불임 원인             256351 non-null  int64
 16  불명확 불임 원인              256351 non-null  int64
 17  불임 원인 - 난관 질환          256351 non-null  int64
 18  불임 원인 - 남성 요인          256351 non-null  int64
 19  불임 원인 - 배란 장애          256351 non-null  int64
 20  불임 원인 - 여성 요인          256351 non-null  int64
 21  불임 원인 - 자궁경부 문제        256351 non-null  int64
 22  불임 원인 - 자궁내막증          256351 non-null  int64
 23  불임 원인 - 정자 농도          256351 non-null  int64
 24  불임 원인 - 정자 면역학적 요인     256351 non-null  int64
 25  불임 원인 - 정자 운동성         256351 non-null  int64
 26  불임 원인 - 정자 형태          256351 non-null  int64
 27  배아 생성 주요 이유            250060 non-null  object
 28  총 시술 횟수                256351 non-null  object
 29  클리닉 내 총 시술 횟수          256351 non-null  object
 30  IVF 시술 횟수              256351 non-null  object
 31  DI 시술 횟수               256351 non-null  object
 32  총 임신 횟수                256351 non-null  object
 33  IVF 임신 횟수              256351 non-null  object
 34  DI 임신 횟수               256351 non-null  object
 35  총 출산 횟수                256351 non-null  object
 36  IVF 출산 횟수              256351 non-null  object
 37  DI 출산 횟수               256351 non-null  object
 38  총 생성 배아 수              250060 non-null  float64
 39  미세주입된 난자 수             250060 non-null  float64
 40  미세주입에서 생성된 배아 수        250060 non-null  float64
 41  이식된 배아 수               250060 non-null  float64
 42  미세주입 배아 이식 수           250060 non-null  float64
 43  저장된 배아 수               250060 non-null  float64
 44  미세주입 후 저장된 배아 수        250060 non-null  float64
 45  해동된 배아 수               250060 non-null  float64
 46  해동 난자 수                250060 non-null  float64
 47  수집된 신선 난자 수            250060 non-null  float64
 48  저장된 신선 난자 수            250060 non-null  float64
 49  혼합된 난자 수               250060 non-null  float64
 50  파트너 정자와 혼합된 난자 수       250060 non-null  float64
 51  기증자 정자와 혼합된 난자 수       250060 non-null  float64
 52  난자 출처                  256351 non-null  object
 53  정자 출처                  256351 non-null  object
 54  난자 기증자 나이              256351 non-null  object
 55  정자 기증자 나이              256351 non-null  object
 56  동결 배아 사용 여부            250060 non-null  float64
 57  신선 배아 사용 여부            250060 non-null  float64
 58  기증 배아 사용 여부            250060 non-null  float64
 59  대리모 여부                 250060 non-null  float64
 60  PGD 시술 여부              2179 non-null    float64
 61  PGS 시술 여부              1929 non-null    float64
 62  난자 채취 경과일              198863 non-null  float64
 63  난자 해동 경과일              1436 non-null    float64
 64  난자 혼합 경과일              202616 non-null  float64
 65  배아 이식 경과일              212785 non-null  float64
 66  배아 해동 경과일              40369 non-null   float64
 67  임신 성공 여부               256351 non-null  int64
dtypes: float64(29), int64(19), object(20)
memory usage: 133.0+ MB

In [ ]:
df.drop(columns=['시술 시기 코드', '임신 시도 또는 마지막 임신 경과 연수' ,'불임 원인 - 여성 요인', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 자궁경부 문제'], inplace=True)

In [ ]:
df['총 시술 횟수'] = df['총 시술 횟수'].str.extract('(\d+)').astype(float)
df['IVF 시술 횟수'] = df['IVF 시술 횟수'].str.extract('(\d+)').astype(float)
df['IVF 임신 횟수'] = df['IVF 임신 횟수'].str.extract('(\d+)').astype(float)
df['DI 시술 횟수'] = df['DI 시술 횟수'].str.extract('(\d+)').astype(float)
df['DI 임신 횟수'] = df['DI 임신 횟수'].str.extract('(\d+)').astype(float)
df['총 임신 횟수'] = df['총 임신 횟수'].str.extract('(\d+)').astype(float)
df['클리닉 내 총 시술 횟수'] = df['클리닉 내 총 시술 횟수'].str.extract('(\d+)').astype(float)
df['총 출산 횟수'] = df['총 출산 횟수'].str.extract('(\d+)').astype(float)
df['DI 출산 횟수'] = df['DI 출산 횟수'].str.extract('(\d+)').astype(float)
df['IVF 출산 횟수'] = df['IVF 출산 횟수'].str.extract('(\d+)').astype(float)

In [ ]:
def extract_age(text):
    numbers = list(map(int, re.findall(r'\d+', text)))  # 모든 숫자 추출
    if numbers:
        return np.mean(numbers)  # 평균 반환
    return 0

## 난자 기증자 나이, 정자 기증자 나이

In [ ]:
df['난자 기증자 나이'] = df['난자 기증자 나이'].apply(extract_age)
df['정자 기증자 나이'] = df['정자 기증자 나이'].apply(extract_age)

## 시술 당시 나이

In [ ]:
df['시술 당시 나이'] = df['시술 당시 나이'].apply(extract_age)

In [ ]:
df['시술 당시 나이'].value_counts()

시술 당시 나이
26.0    102476
36.0     57780
38.5     39247
41.0     37348
43.5     12253
47.5      6918
0.0        329
Name: count, dtype: int64

In [ ]:
df[df['시술 당시 나이']=='알 수 없음']['임신 성공 여부'].value_counts()

Series([], Name: count, dtype: int64)

In [ ]:
# '시술 당시 나이'가 '알 수 없음'인 경우 50으로 대체
df.loc[df['시술 당시 나이'] == '알 수 없음', '시술 당시 나이'] = 50

## 시술 관련 열

In [ ]:
df['특정 시술 유형'] = df['특정 시술 유형'].fillna('Unknown')

In [ ]:
# '세부 조합 시행 여부' => ':'이 있으면 1, 없으면 0
df['세부 조합 시행 여부'] = df['특정 시술 유형'].str.contains(':').astype(int)

# '복합적인 시술 시행 여부' =>  '/'이 있으면 1, 없으면 0
df['복합적인 시술 시행 여부'] = df['특정 시술 유형'].str.contains('/').astype(int)

In [ ]:
df = df.drop(columns = ['특정 시술 유형','시술 유형'])

## 배아 생성 주요 이유

In [ ]:
df['현재 시술용 배아 생성'] = df["배아 생성 주요 이유"].apply(lambda x: 1 if "현재 시술용" in str(x) else 0)
df['배아/난자 저장 또는 기증 여부'] = df["배아 생성 주요 이유"].apply(
    lambda x: 1 if any(keyword in str(x) for keyword in ["배아 저장용", "난자 저장용", "기증용"]) else 0
)

df = df.drop(columns = ['배아 생성 주요 이유'])

## PGD, PGS

PGS 시술 => 배아를 자궁에 이식하기 전에 염색체 이상 여부를 검사하는 과정
- 모든 IVF 환자에게 가능
- 염색체 개수 이상을 검사
- 보통 하는 경우 : 정자의 운동성 저하, 형태 이상, 고령 임신, 반복적인 착상 실패, 배아를 기증한 경우

착상 전 유전 진단 사용 여부 == 0

불임 원인 - 정자 농도 == 0

불임 원인 - 정자 운동성 == 0

불임 원인 - 정자 형태 ==0

PGD == null

난자 채취 경과일 == 0 or null

현재 시술용 배아 생성 == 1

배아/난자 저장 또는 기증 여부 =0

In [ ]:
# 조건에 맞는 데이터를 필터링
filtered_df = df[
    (df['착상 전 유전 진단 사용 여부'] == 0) &
    (df['착상 전 유전 검사 사용 여부'] == 1) &
    (df['불임 원인 - 정자 농도'] == 0) &
    (df['불임 원인 - 정자 운동성'] == 0) &
    (df['불임 원인 - 정자 형태'] == 0) &
    (df['PGD 시술 여부'].isnull()) &
    ((df['난자 채취 경과일'] == 0) | (df['난자 채취 경과일'].isnull())) &
    (df['현재 시술용 배아 생성'] == 1) &
    (df['배아/난자 저장 또는 기증 여부'] == 0)

]

# 해당 조건을 만족하는 경우의 수 확인
matching_cases = len(filtered_df)

# 결과 출력
matching_cases

1933

In [ ]:
# 해당 조건을 만족하는 행들의 'PGS 시술 여부' 값을 1.0으로 변경
df.loc[filtered_df.index, 'PGS 시술 여부'] = 1.0

In [ ]:
df['PGS 시술 여부'].isna().sum()

254418

In [ ]:
df['PGD 시술 여부'].isna().sum()

254172

In [ ]:
df['PGD 시술 여부'].value_counts()

PGD 시술 여부
1.0    2179
Name: count, dtype: int64

In [ ]:
# 조건에 맞는 데이터를 필터링
filtered_df = df[
    (df['착상 전 유전 진단 사용 여부'] == 1) &
    (df['착상 전 유전 검사 사용 여부'] == 0) &
    (df['불임 원인 - 정자 농도'] == 0) &
    (df['불임 원인 - 정자 운동성'] == 0) &
    (df['불임 원인 - 정자 형태'] == 0) &
    (df['PGS 시술 여부'].isnull())
]

# 해당 조건을 만족하는 경우의 수 확인
matching_cases = len(filtered_df)

# 결과 출력
matching_cases

0

In [ ]:
# 해당 조건을 만족하는 행들의 'PGD 시술 여부' 값을 1.0으로 변경
df.loc[filtered_df.index, 'PGD 시술 여부'] = 1.0

In [ ]:
df['PGD 시술 여부'] = df['PGD 시술 여부'].fillna(0.0)

In [ ]:
df['PGS 시술 여부']= df['PGS 시술 여부'].fillna(0.0)

## 불임 관련 열

In [ ]:
df["남성 요인 불임 여부"] = df[["남성 주 불임 원인", "남성 부 불임 원인", '불임 원인 - 남성 요인', '불임 원인 - 정자 농도', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태']].max(axis=1)
df["여성 요인 불임 여부"] = df[["여성 주 불임 원인", "여성 부 불임 원인",'불임 원인 - 난관 질환', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증']].max(axis=1)
df["불명확 원인 불임 여부"] = df["불명확 불임 원인"]

In [ ]:
df = df.drop(columns = ['남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '불명확 불임 원인',
                        '불임 원인 - 남성 요인', '불임 원인 - 정자 농도', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태',
                        '불임 원인 - 난관 질환', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증'])

## 착상 전 유전 검사 사용 여부, 착상 전 유전 진단 사용 여부

In [ ]:
df['착상 전 유전 검사 사용 여부'].value_counts()

착상 전 유전 검사 사용 여부
1.0    2718
Name: count, dtype: int64

In [ ]:
df = df.drop(columns=['착상 전 유전 검사 사용 여부'])

In [ ]:
df['착상 전 유전 진단 사용 여부'].value_counts()

착상 전 유전 진단 사용 여부
0.0    246864
1.0      3196
Name: count, dtype: int64

## 배아 사용 여부



```
57  동결 배아 사용 여부            250060 non-null  float64
 58  신선 배아 사용 여부            250060 non-null  float64
 59  기증 배아 사용 여부            250060 non-null  float64
```

In [ ]:
df.loc[(df['해동된 배아 수'] == 0.0) & (df['동결 배아 사용 여부'].isna()), '동결 배아 사용 여부'] = 0.0

In [ ]:
## 신선 배아 사용 여부의 값이 null이라면, 총 생성 배아 수의 값이 0.0이였음
df.loc[(df['총 생성 배아 수'] == 0.0) & (df['신선 배아 사용 여부'].isna()), '신선 배아 사용 여부'] = 0.0

## 난자, 정자 출처

In [ ]:
df.loc[(df['기증 배아 사용 여부'] == 1.0), '난자 출처'] = '기증 제공'
df.loc[(df['기증 배아 사용 여부'] == 1.0), '정자 출처'] = '기증 제공'

df.loc[df['난자 출처'] == '알 수 없음', '난자 출처'] = '본인 제공'

df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 0),
    '정자 출처'
] = '기증 제공'
df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 1),
    '정자 출처'
] = '배우자 및 기증 제공'
df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] == 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 1),
    '정자 출처'
] = '배우자 제공'
df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 0),
    '정자 출처'
] = '기증 제공'
df.loc[df['정자 출처'] == '미할당', '정자 출처'] = '배우자 제공'

# One-Hot Encoding
one_hot_features=['난자 출처','정자 출처']
df = pd.get_dummies(df, columns=one_hot_features)

## 대리모

In [ ]:
df.loc[
    ((df['신선 배아 사용 여부'] == 1) | (df['동결 배아 사용 여부'] == 1)) & (df['대리모 여부'].isnull()),
    '대리모 여부'
] = 1

In [ ]:
df['대리모 여부'].value_counts()

대리모 여부
0.0    249011
1.0      1049
Name: count, dtype: int64

## 경과일


```
58  난자 채취 경과일              198864 non-null  float64
 59  난자 해동 경과일              1436 non-null    float64
 60  난자 혼합 경과일              202617 non-null  float64
 61  배아 이식 경과일              219077 non-null  float64
 62  배아 해동 경과일              46661 non-null   float64
```

In [ ]:
df['난자 채취 경과일'].value_counts()

난자 채취 경과일
0.0    198863
Name: count, dtype: int64

In [ ]:
df = df.drop(columns = ['난자 채취 경과일'])

In [ ]:
df['난자 해동 경과일'].value_counts()

난자 해동 경과일
0.0    1434
1.0       2
Name: count, dtype: int64

## 배란 유도 유형

In [ ]:
# 유형이 기록된 건수가 2건이라, 잘 적지 않는 듯 하여 1, 0으로 표시하는 방법으로 진행하면 어떨지

df['배란 유도 유형'] = df['배란 유도 유형'].apply(lambda x: 0 if x == "알 수 없음" else 1)

# 데이터 확인

In [ ]:
df=df.fillna(0)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256351 entries, 0 to 256350
Data columns (total 56 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   시술 당시 나이           256351 non-null  float64
 1   배란 자극 여부           256351 non-null  int64
 2   배란 유도 유형           256351 non-null  int64
 3   단일 배아 이식 여부        256351 non-null  float64
 4   착상 전 유전 진단 사용 여부   256351 non-null  float64
 5   부부 주 불임 원인         256351 non-null  int64
 6   부부 부 불임 원인         256351 non-null  int64
 7   총 시술 횟수            256351 non-null  float64
 8   클리닉 내 총 시술 횟수      256351 non-null  float64
 9   IVF 시술 횟수          256351 non-null  float64
 10  DI 시술 횟수           256351 non-null  float64
 11  총 임신 횟수            256351 non-null  float64
 12  IVF 임신 횟수          256351 non-null  float64
 13  DI 임신 횟수           256351 non-null  float64
 14  총 출산 횟수            256351 non-null  float64
 15  IVF 출산 횟수          256351 non-null  float64
 16  DI 출산 횟수           256351 non-null  float64
 17  총 생성 배아 수          256351 non-null  float64
 18  미세주입된 난자 수         256351 non-null  float64
 19  미세주입에서 생성된 배아 수    256351 non-null  float64
 20  이식된 배아 수           256351 non-null  float64
 21  미세주입 배아 이식 수       256351 non-null  float64
 22  저장된 배아 수           256351 non-null  float64
 23  미세주입 후 저장된 배아 수    256351 non-null  float64
 24  해동된 배아 수           256351 non-null  float64
 25  해동 난자 수            256351 non-null  float64
 26  수집된 신선 난자 수        256351 non-null  float64
 27  저장된 신선 난자 수        256351 non-null  float64
 28  혼합된 난자 수           256351 non-null  float64
 29  파트너 정자와 혼합된 난자 수   256351 non-null  float64
 30  기증자 정자와 혼합된 난자 수   256351 non-null  float64
 31  난자 기증자 나이          256351 non-null  float64
 32  정자 기증자 나이          256351 non-null  float64
 33  동결 배아 사용 여부        256351 non-null  float64
 34  신선 배아 사용 여부        256351 non-null  float64
 35  기증 배아 사용 여부        256351 non-null  float64
 36  대리모 여부             256351 non-null  float64
 37  PGD 시술 여부          256351 non-null  float64
 38  PGS 시술 여부          256351 non-null  float64
 39  난자 해동 경과일          256351 non-null  float64
 40  난자 혼합 경과일          256351 non-null  float64
 41  배아 이식 경과일          256351 non-null  float64
 42  배아 해동 경과일          256351 non-null  float64
 43  임신 성공 여부           256351 non-null  int64
 44  세부 조합 시행 여부        256351 non-null  int64
 45  복합적인 시술 시행 여부      256351 non-null  int64
 46  현재 시술용 배아 생성       256351 non-null  int64
 47  배아/난자 저장 또는 기증 여부  256351 non-null  int64
 48  남성 요인 불임 여부        256351 non-null  int64
 49  여성 요인 불임 여부        256351 non-null  int64
 50  불명확 원인 불임 여부       256351 non-null  int64
 51  난자 출처_기증 제공        256351 non-null  bool
 52  난자 출처_본인 제공        256351 non-null  bool
 53  정자 출처_기증 제공        256351 non-null  bool
 54  정자 출처_배우자 및 기증 제공  256351 non-null  bool
 55  정자 출처_배우자 제공       256351 non-null  bool
dtypes: bool(5), float64(39), int64(12)
memory usage: 101.0 MB

In [ ]:
df.to_csv("train_fin.csv")

In [ ]:
df_test = pd.read_csv("test.csv").drop(columns=['ID'])

In [ ]:
def process_test_data(df):
  df.drop(columns=['시술 시기 코드', '임신 시도 또는 마지막 임신 경과 연수' ,'불임 원인 - 여성 요인', '불임 원인 - 정자 면역학적 요인', '불임 원인 - 자궁경부 문제'], inplace=True)
  df['총 시술 횟수'] = df['총 시술 횟수'].str.extract('(\d+)').astype(float)
  df['IVF 시술 횟수'] = df['IVF 시술 횟수'].str.extract('(\d+)').astype(float)
  df['IVF 임신 횟수'] = df['IVF 임신 횟수'].str.extract('(\d+)').astype(float)
  df['DI 시술 횟수'] = df['DI 시술 횟수'].str.extract('(\d+)').astype(float)
  df['DI 임신 횟수'] = df['DI 임신 횟수'].str.extract('(\d+)').astype(float)
  df['총 임신 횟수'] = df['총 임신 횟수'].str.extract('(\d+)').astype(float)
  df['클리닉 내 총 시술 횟수'] = df['클리닉 내 총 시술 횟수'].str.extract('(\d+)').astype(float)
  df['총 출산 횟수'] = df['총 출산 횟수'].str.extract('(\d+)').astype(float)
  df['DI 출산 횟수'] = df['DI 출산 횟수'].str.extract('(\d+)').astype(float)
  df['IVF 출산 횟수'] = df['IVF 출산 횟수'].str.extract('(\d+)').astype(float)

  df['난자 기증자 나이'] = df['난자 기증자 나이'].apply(extract_age)
  df['정자 기증자 나이'] = df['정자 기증자 나이'].apply(extract_age)

  df['시술 당시 나이'] = df['시술 당시 나이'].apply(extract_age)
  df.loc[df['시술 당시 나이'] == '알 수 없음', '시술 당시 나이'] = 50

  df['특정 시술 유형'] = df['특정 시술 유형'].fillna('Unknown')
  df['세부 조합 시행 여부'] = df['특정 시술 유형'].str.contains(':').astype(int)
  df['복합적인 시술 시행 여부'] = df['특정 시술 유형'].str.contains('/').astype(int)
  df = df.drop(columns = ['특정 시술 유형','시술 유형'])

  df['현재 시술용 배아 생성'] = df["배아 생성 주요 이유"].apply(lambda x: 1 if "현재 시술용" in str(x) else 0)
  df['배아/난자 저장 또는 기증 여부'] = df["배아 생성 주요 이유"].apply(
    lambda x: 1 if any(keyword in str(x) for keyword in ["배아 저장용", "난자 저장용", "기증용"]) else 0
  )
  df = df.drop(columns = ['배아 생성 주요 이유'])

  filtered_df = df[
    (df['착상 전 유전 진단 사용 여부'] == 0) &
    (df['착상 전 유전 검사 사용 여부'] == 1) &
    (df['불임 원인 - 정자 농도'] == 0) &
    (df['불임 원인 - 정자 운동성'] == 0) &
    (df['불임 원인 - 정자 형태'] == 0) &
    (df['PGD 시술 여부'].isnull()) &
    ((df['난자 채취 경과일'] == 0) | (df['난자 채취 경과일'].isnull())) &
    (df['현재 시술용 배아 생성'] == 1) &
    (df['배아/난자 저장 또는 기증 여부'] == 0)
  ]
  df.loc[filtered_df.index, 'PGS 시술 여부'] = 1.0

  filtered_df = df[
    (df['착상 전 유전 진단 사용 여부'] == 1) &
    (df['착상 전 유전 검사 사용 여부'] == 0) &
    (df['불임 원인 - 정자 농도'] == 0) &
    (df['불임 원인 - 정자 운동성'] == 0) &
    (df['불임 원인 - 정자 형태'] == 0) &
    (df['PGS 시술 여부'].isnull())
  ]
  df.loc[filtered_df.index, 'PGD 시술 여부'] = 1.0

  df["남성 요인 불임 여부"] = df[["남성 주 불임 원인", "남성 부 불임 원인", '불임 원인 - 남성 요인', '불임 원인 - 정자 농도', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태']].max(axis=1)
  df["여성 요인 불임 여부"] = df[["여성 주 불임 원인", "여성 부 불임 원인",'불임 원인 - 난관 질환', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증']].max(axis=1)
  df["불명확 원인 불임 여부"] = df["불명확 불임 원인"]
  df = df.drop(columns = ['남성 주 불임 원인', '남성 부 불임 원인', '여성 주 불임 원인', '여성 부 불임 원인', '불명확 불임 원인',
                        '불임 원인 - 남성 요인', '불임 원인 - 정자 농도', '불임 원인 - 정자 운동성', '불임 원인 - 정자 형태',
                        '불임 원인 - 난관 질환', '불임 원인 - 배란 장애', '불임 원인 - 자궁내막증'])

  df = df.drop(columns=['착상 전 유전 검사 사용 여부'])
  df.loc[(df['해동된 배아 수'] == 0.0) & (df['동결 배아 사용 여부'].isna()), '동결 배아 사용 여부'] = 0.0
  df.loc[(df['총 생성 배아 수'] == 0.0) & (df['신선 배아 사용 여부'].isna()), '신선 배아 사용 여부'] = 0.0

  df.loc[(df['기증 배아 사용 여부'] == 1.0), '난자 출처'] = '기증 제공'
  df.loc[(df['기증 배아 사용 여부'] == 1.0), '정자 출처'] = '기증 제공'

  df.loc[df['난자 출처'] == '알 수 없음', '난자 출처'] = '본인 제공'

  df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 0),
    '정자 출처'
  ] = '기증 제공'
  df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 1),
    '정자 출처'
  ] = '배우자 및 기증 제공'
  df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] == 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 1),
    '정자 출처'
  ] = '배우자 제공'
  df.loc[
    (df['정자 출처'] == '미할당') &
    (df['정자 기증자 나이'] != 0) &
    (df['파트너 정자와 혼합된 난자 수'] == 0),
    '정자 출처'
  ] = '기증 제공'
  df.loc[df['정자 출처'] == '미할당', '정자 출처'] = '배우자 제공'
  # One-Hot Encoding
  one_hot_features=['난자 출처','정자 출처']
  df = pd.get_dummies(df, columns=one_hot_features)
  df.loc[
    ((df['신선 배아 사용 여부'] == 1) | (df['동결 배아 사용 여부'] == 1)) & (df['대리모 여부'].isnull()),
    '대리모 여부'
  ] = 1

  df = df.drop(columns = ['난자 채취 경과일'])
  df['배란 유도 유형'] = df['배란 유도 유형'].apply(lambda x: 0 if x == "알 수 없음" else 1)

  df=df.fillna(0)
  return df

In [ ]:
df_test = process_test_data(df_test)

In [ ]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90067 entries, 0 to 90066
Data columns (total 55 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   시술 당시 나이           90067 non-null  float64
 1   배란 자극 여부           90067 non-null  int64
 2   배란 유도 유형           90067 non-null  int64
 3   단일 배아 이식 여부        90067 non-null  float64
 4   착상 전 유전 진단 사용 여부   90067 non-null  float64
 5   부부 주 불임 원인         90067 non-null  int64
 6   부부 부 불임 원인         90067 non-null  int64
 7   총 시술 횟수            90067 non-null  float64
 8   클리닉 내 총 시술 횟수      90067 non-null  float64
 9   IVF 시술 횟수          90067 non-null  float64
 10  DI 시술 횟수           90067 non-null  float64
 11  총 임신 횟수            90067 non-null  float64
 12  IVF 임신 횟수          90067 non-null  float64
 13  DI 임신 횟수           90067 non-null  float64
 14  총 출산 횟수            90067 non-null  float64
 15  IVF 출산 횟수          90067 non-null  float64
 16  DI 출산 횟수           90067 non-null  float64
 17  총 생성 배아 수          90067 non-null  float64
 18  미세주입된 난자 수         90067 non-null  float64
 19  미세주입에서 생성된 배아 수    90067 non-null  float64
 20  이식된 배아 수           90067 non-null  float64
 21  미세주입 배아 이식 수       90067 non-null  float64
 22  저장된 배아 수           90067 non-null  float64
 23  미세주입 후 저장된 배아 수    90067 non-null  float64
 24  해동된 배아 수           90067 non-null  float64
 25  해동 난자 수            90067 non-null  float64
 26  수집된 신선 난자 수        90067 non-null  float64
 27  저장된 신선 난자 수        90067 non-null  float64
 28  혼합된 난자 수           90067 non-null  float64
 29  파트너 정자와 혼합된 난자 수   90067 non-null  float64
 30  기증자 정자와 혼합된 난자 수   90067 non-null  float64
 31  난자 기증자 나이          90067 non-null  float64
 32  정자 기증자 나이          90067 non-null  float64
 33  동결 배아 사용 여부        90067 non-null  float64
 34  신선 배아 사용 여부        90067 non-null  float64
 35  기증 배아 사용 여부        90067 non-null  float64
 36  대리모 여부             90067 non-null  float64
 37  PGD 시술 여부          90067 non-null  float64
 38  PGS 시술 여부          90067 non-null  float64
 39  난자 해동 경과일          90067 non-null  float64
 40  난자 혼합 경과일          90067 non-null  float64
 41  배아 이식 경과일          90067 non-null  float64
 42  배아 해동 경과일          90067 non-null  float64
 43  세부 조합 시행 여부        90067 non-null  int64
 44  복합적인 시술 시행 여부      90067 non-null  int64
 45  현재 시술용 배아 생성       90067 non-null  int64
 46  배아/난자 저장 또는 기증 여부  90067 non-null  int64
 47  남성 요인 불임 여부        90067 non-null  int64
 48  여성 요인 불임 여부        90067 non-null  int64
 49  불명확 원인 불임 여부       90067 non-null  int64
 50  난자 출처_기증 제공        90067 non-null  bool
 51  난자 출처_본인 제공        90067 non-null  bool
 52  정자 출처_기증 제공        90067 non-null  bool
 53  정자 출처_배우자 및 기증 제공  90067 non-null  bool
 54  정자 출처_배우자 제공       90067 non-null  bool
dtypes: bool(5), float64(39), int64(11)
memory usage: 34.8 MB

In [ ]:
df_test.to_csv("test_fin.csv")

In [ ]:
df_test

,시술 당시 나이,배란 자극 여부,배란 유도 유형,단일 배아 이식 여부,착상 전 유전 진단 사용 여부,부부 주 불임 원인,부부 부 불임 원인,총 시술 횟수,클리닉 내 총 시술 횟수,IVF 시술 횟수,...,현재 시술용 배아 생성,배아/난자 저장 또는 기증 여부,남성 요인 불임 여부,여성 요인 불임 여부,불명확 원인 불임 여부,난자 출처_기증 제공,난자 출처_본인 제공,정자 출처_기증 제공,정자 출처_배우자 및 기증 제공,정자 출처_배우자 제공
0,36.0,1,1,0.0,0.0,0,0,1.0,1.0,1.0,...,1,0,0,0,1,False,True,False,False,True
1,26.0,1,1,0.0,0.0,0,0,0.0,0.0,0.0,...,1,0,1,0,0,False,True,True,False,False
2,41.0,1,1,0.0,0.0,0,0,0.0,0.0,0.0,...,1,0,0,0,0,False,True,False,False,True
3,41.0,1,1,0.0,0.0,0,0,0.0,0.0,0.0,...,1,0,0,0,1,False,True,False,False,True
4,36.0,1,1,0.0,0.0,0,0,1.0,1.0,1.0,...,1,0,0,1,0,False,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90062,26.0,1,1,0.0,1.0,0,0,2.0,2.0,2.0,...,0,1,0,0,0,False,True,False,False,True
90063,43.5,0,0,0.0,0.0,0,0,6.0,4.0,6.0,...,1,0,0,0,0,True,False,False,False,True
90064,26.0,0,0,1.0,0.0,0,0,2.0,0.0,2.0,...,1,0,0,1,0,True,False,False,False,True
90065,43.5,0,0,0.0,0.0,0,0,6.0,2.0,4.0,...,1,0,0,0,0,False,True,True,False,False
90066,26.0,1,1,0.0,0.0,0,0,4.0,0.0,4.0,...,1,0,0,0,0,False,True,False,False,True